language: python

sudo: false

env:
    - TOX_ENV=py36-flake8
    - TOX_ENV=py36-docs
    - TOX_ENV=py36-django3.0-drf3.10
    - TOX_ENV=py36-django3.0-drf3.11
    - TOX_ENV=py36-django3.0-drf3.12
    - TOX_ENV=py36-django3.1-drf3.10
    - TOX_ENV=py36-django3.1-drf3.11
    - TOX_ENV=py36-django3.1-drf3.12

    - TOX_ENV=py37-django3.0-drf3.10
    - TOX_ENV=py37-django3.0-drf3.11
    - TOX_ENV=py37-django3.0-drf3.12
    - TOX_ENV=py37-django3.1-drf3.10
    - TOX_ENV=py37-django3.1-drf3.11
    - TOX_ENV=py37-django3.1-drf3.12

    - TOX_ENV=py38-django3.0-drf3.10
    - TOX_ENV=py38-django3.0-drf3.11
    - TOX_ENV=py38-django3.0-drf3.12
    - TOX_ENV=py38-django3.1-drf3.10
    - TOX_ENV=py38-django3.1-drf3.11
    - TOX_ENV=py38-django3.1-drf3.12

    - TOX_ENV=py39-django3.0-drf3.10
    - TOX_ENV=py39-django3.0-drf3.11
    - TOX_ENV=py39-django3.0-drf3.12
    - TOX_ENV=py39-django3.1-drf3.10
    - TOX_ENV=py39-django3.1-drf3.11
    - TOX_ENV=py39-django3.1-drf3.12

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
