site_name: DRF dog
repo_url: https://github.com/coaxsoft/drf_dog
theme:
  name: material
  favicon: assets/favicon.png
  icon:
    logo: material/axe
  palette:
    primary: blue
  features:
    - navigation.instant
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
nav:
  - Serializers: serializers.md
  - Release Notes: release_notes.md
